// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/aanjay368/schedule-lion/backend/internal/config"
	"github.com/aanjay368/schedule-lion/backend/internal/exception"
	"github.com/aanjay368/schedule-lion/backend/internal/handler"
	"github.com/aanjay368/schedule-lion/backend/internal/pkg"
	"github.com/aanjay368/schedule-lion/backend/internal/repository"
	"github.com/aanjay368/schedule-lion/backend/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	translator := pkg.NewTranslator()
	configConfig := config.LoadConfig()
	db := pkg.NewDB(configConfig)
	validate := pkg.NewValidator(translator, db)
	exceptionHandler := &exception.ExceptionHandler{
		Validate:   validate,
		Translator: translator,
	}
	app := pkg.NewFiberApp(exceptionHandler)
	divisionRepositoryImpl := &repository.DivisionRepositoryImpl{}
	divisionServiceImpl := &service.DivisionServiceImpl{
		DivisionRepository: divisionRepositoryImpl,
		DB:                 db,
	}
	divisionHandlerImpl := &handler.DivisionHandlerImpl{
		DivisionService: divisionServiceImpl,
	}
	userRepositoryImpl := &repository.UserRepositoryImpl{}
	authServiceImpl := &service.AuthServiceImpl{
		UserRepository: userRepositoryImpl,
		Config:         configConfig,
		DB:             db,
		Validator:      validate,
	}
	authHandlerImpl := &handler.AuthHandlerImpl{
		AuthService: authServiceImpl,
	}
	userServiceImpl := &service.UserServiceImpl{
		UserRepository: userRepositoryImpl,
		DB:             db,
	}
	userHandlerImpl := &handler.UserHandlerImpl{
		UserService: userServiceImpl,
	}
	employeeRepositoryImpl := &repository.EmployeeRepositoryImpl{}
	employeeServiceImpl := &service.EmployeeServiceImpl{
		EmployeeRepository: employeeRepositoryImpl,
		DivisionRepository: divisionRepositoryImpl,
		UserRepository:     userRepositoryImpl,
		DB:                 db,
		Validator:          validate,
		Config:             configConfig,
	}
	employeeHandlerImpl := &handler.EmployeeHandlerImpl{
		EmployeeService: employeeServiceImpl,
	}
	shiftRepositoryImpl := &repository.ShiftRepositoryImpl{}
	shiftServiceImpl := &service.ShiftServiceImpl{
		ShiftRepository:    shiftRepositoryImpl,
		DivisionRepository: divisionRepositoryImpl,
		Validator:          validate,
		DB:                 db,
	}
	shiftHandlerImpl := &handler.ShiftHandlerImpl{
		ShiftService: shiftServiceImpl,
	}
	server := &Server{
		App:             app,
		DivisionHandler: divisionHandlerImpl,
		AuthHandler:     authHandlerImpl,
		UserHandler:     userHandlerImpl,
		EmployeeHandler: employeeHandlerImpl,
		ShiftHandler:    shiftHandlerImpl,
		Config:          configConfig,
	}
	return server, nil
}

// wire.go:

var divisionSet = wire.NewSet(wire.Struct(new(repository.DivisionRepositoryImpl), "*"), wire.Bind(new(repository.DivisionRepository), new(*repository.DivisionRepositoryImpl)), wire.Struct(new(service.DivisionServiceImpl), "*"), wire.Bind(new(service.DivisionService), new(*service.DivisionServiceImpl)), wire.Struct(new(handler.DivisionHandlerImpl), "*"), wire.Bind(new(handler.DivisionHandler), new(*handler.DivisionHandlerImpl)))

var authSet = wire.NewSet(wire.Struct(new(service.AuthServiceImpl), "*"), wire.Bind(new(service.AuthService), new(*service.AuthServiceImpl)), wire.Struct(new(handler.AuthHandlerImpl), "*"), wire.Bind(new(handler.AuthHandler), new(*handler.AuthHandlerImpl)))

var userSet = wire.NewSet(wire.Struct(new(repository.UserRepositoryImpl), "*"), wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)), wire.Struct(new(service.UserServiceImpl), "*"), wire.Bind(new(service.UserService), new(*service.UserServiceImpl)), wire.Struct(new(handler.UserHandlerImpl), "*"), wire.Bind(new(handler.UserHandler), new(*handler.UserHandlerImpl)))

var employeeSet = wire.NewSet(wire.Struct(new(repository.EmployeeRepositoryImpl), "*"), wire.Bind(new(repository.EmployeeRepository), new(*repository.EmployeeRepositoryImpl)), wire.Struct(new(service.EmployeeServiceImpl), "*"), wire.Bind(new(service.EmployeeService), new(*service.EmployeeServiceImpl)), wire.Struct(new(handler.EmployeeHandlerImpl), "*"), wire.Bind(new(handler.EmployeeHandler), new(*handler.EmployeeHandlerImpl)))

var shiftSet = wire.NewSet(wire.Struct(new(repository.ShiftRepositoryImpl), "*"), wire.Bind(new(repository.ShiftRepository), new(*repository.ShiftRepositoryImpl)), wire.Struct(new(service.ShiftServiceImpl), "*"), wire.Bind(new(service.ShiftService), new(*service.ShiftServiceImpl)), wire.Struct(new(handler.ShiftHandlerImpl), "*"), wire.Bind(new(handler.ShiftHandler), new(*handler.ShiftHandlerImpl)))
